add_test([=[GetNextHead.RightWrap]=]  F:/snake-cli/tests/Debug/snake_tests.exe [==[--gtest_filter=GetNextHead.RightWrap]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GetNextHead.RightWrap]=]  PROPERTIES WORKING_DIRECTORY F:/snake-cli/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GetNextHead.LeftWrap]=]  F:/snake-cli/tests/Debug/snake_tests.exe [==[--gtest_filter=GetNextHead.LeftWrap]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GetNextHead.LeftWrap]=]  PROPERTIES WORKING_DIRECTORY F:/snake-cli/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GetNextHead.UpWrap]=]  F:/snake-cli/tests/Debug/snake_tests.exe [==[--gtest_filter=GetNextHead.UpWrap]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GetNextHead.UpWrap]=]  PROPERTIES WORKING_DIRECTORY F:/snake-cli/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GetNextHead.DownWrap]=]  F:/snake-cli/tests/Debug/snake_tests.exe [==[--gtest_filter=GetNextHead.DownWrap]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GetNextHead.DownWrap]=]  PROPERTIES WORKING_DIRECTORY F:/snake-cli/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SpawnFood.NotOnSnakeOrPoison]=]  F:/snake-cli/tests/Debug/snake_tests.exe [==[--gtest_filter=SpawnFood.NotOnSnakeOrPoison]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SpawnFood.NotOnSnakeOrPoison]=]  PROPERTIES WORKING_DIRECTORY F:/snake-cli/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SpawnPoison.NotOnSnakeOrFood]=]  F:/snake-cli/tests/Debug/snake_tests.exe [==[--gtest_filter=SpawnPoison.NotOnSnakeOrFood]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SpawnPoison.NotOnSnakeOrFood]=]  PROPERTIES WORKING_DIRECTORY F:/snake-cli/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UpdateHighScores.WritesTop10WithCurrentScore]=]  F:/snake-cli/tests/Debug/snake_tests.exe [==[--gtest_filter=UpdateHighScores.WritesTop10WithCurrentScore]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UpdateHighScores.WritesTop10WithCurrentScore]=]  PROPERTIES WORKING_DIRECTORY F:/snake-cli/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  snake_tests_TESTS GetNextHead.RightWrap GetNextHead.LeftWrap GetNextHead.UpWrap GetNextHead.DownWrap SpawnFood.NotOnSnakeOrPoison SpawnPoison.NotOnSnakeOrFood UpdateHighScores.WritesTop10WithCurrentScore)
